### ISSUE TITLE
Covert function-based primitives to class

### ISSUE THREAD

**Issue by luofanghao** [usc-isi-i2/dsbox-profiling#7]
Hi I just wrapped our profiler within a Profiler class, you can check in [refactor branch](https://github.com/usc-isi-i2/dsbox-profiling/tree/refactor). The usage is like 

```python
from dsbox.datapreprocessing.profiler import Profiler

profiler = Profiler()
jsonResult = profiler.profile_data('testData.csv')
```

Do we need to do something to the giant profile_data() method? And the helper function files "feature_compute_hih.py" "feature_compute_lfh.py" ? @kyao @rpedsel

**Comment by kyao** [comment]
Let's merge the refactor branch into the master first.

With respect to the giant profile_data() method, we could add an optional column argument to return only profile of particular columns. 

Another way would be to have methods that return specific type of profiles.

**Comment by luofanghao** [comment]
Okay! Let's keep the current version now. When needed, we can add more wrapper functions on it.
